---
feeds:
- http://composition.al/atom.xml
- http://funnelfiasco.com/blog/feed/
- http://soulcutter.com/feed.xml
- http://www.courtnycotten.com/feed/
- http://www.mileszs.com/feed.xml
- https://blog.grotenhuis.info/feed.xml
- https://carloslem.us/blog/index.xml
- https://dev.jimgrey.net/feed/
- https://fuzzyblog.io/blog/feed.xml
- https://jacob.jkrall.net/rss.xml
- https://mdswanson.com/atom.xml
- https://oldchestnut.work/feed.xml
- https://roadfiresoftware.com/feed/
- https://trycatch.dev/rss.xml
title: IndyHackers Planet
about: Aggregating the IndyHackers Community
root_url: http://indyhackers-planet.herokuapp.com/
