---
feeds:
- http://arktronic.com/rss.xml
- http://blog.chrisvannoy.com/feed/
- http://blog.codatory.com/posts.rss
- http://mdswanson.com/atom.xml
- http://mileszs.com/atom.xml
- http://todd.grotenhuis.info/atom.xml
title: IndyHackers Planet
about: Aggregating the IndyHackers Community
root_url: http://indyhackers-planet.herokuapp.com/
