---
feeds:
- http://arktronic.com/rss.xml
- http://blog.chrisvannoy.com/rss/
- http://blog.funnelfiasco.com/?feed=rss2
- http://blog.sephonic.us/rss
- http://blog.theincredibleholk.org/atom.xml
- http://composition.al/atom.xml
- http://courtnycotten.com/feed/
- http://davefancher.com/feed/
- http://davydotcom.com/blog.rss
- http://dwradcliffe.com/atom.xml
- http://evanwalsh.net/atom.xml
- http://feeds.feedburner.com/aaronbushnell
- http://feeds.feedburner.com/codebtbytescom
- http://feeds.feedburner.com/funkablog-atom
- http://jacob.jkrall.net/rss.xml
- http://joeldart.wordpress.com/feed/
- http://jon-nolen.blogspot.com/feeds/posts/default
- http://larry-price.com/atom.xml
- http://mafellows.com/rss
- http://massive-robot.blogspot.com/feeds/posts/default
- http://mike-rogers.github.io/atom.xml
- http://milamsoft.blogspot.com
- http://mileszs.com/atom.xml
- http://myotherpants.com/category/worksafe/feed/
- http://pickardayune.com/atom.xml
- http://roadfiresoftware.com/blog/feed/
- http://softwaresaltmines.com/feed/
- http://todd.grotenhuis.info/atom.xml
- http://verticalaligncenter.com/blog?format=rss
- http://work.stevegrossi.com/feed.xml
- http://www.mdswanson.com/atom.xml
- http://www.schmonz.com/rss/
- https://codatory.com/rss/
title: IndyHackers Planet
about: Aggregating the IndyHackers Community
root_url: http://indyhackers-planet.herokuapp.com/
