---
feeds:
- http://blog.funnelfiasco.com/?feed=rss2
- http://composition.al/atom.xml
- http://courtnycotten.com/feed/
- http://fuzzyblog.io/blog/feed
- http://jacob.jkrall.net/rss.xml
- http://mileszs.github.com/feed.xml
- http://www.mdswanson.com/atom.xml
- https://blog.grotenhuis.info/feed.xml
- https://dev.jimgrey.net/feed/
- https://roadfiresoftware.com/feed/
- https://trycatch.dev/rss.xml
title: IndyHackers Planet
about: Aggregating the IndyHackers Community
root_url: http://indyhackers-planet.herokuapp.com/
