---
feeds:
- https://codatory.com/rss/
- http://funnelfiasco.com/blog/feed/
- http://soulcutter.com/feed.xml
- http://www.mileszs.com/feed.xml
- https://aaron.milam.io/feed.xml
- https://blog.grotenhuis.info/feed.xml
- https://carloslem.us/blog/index.xml
- https://creatorswhocode.com/feed.xml
- https://dev.jimgrey.net/feed/
- https://fuzzyblog.io/blog/feed.xml
- https://jacob.jkrall.net/rss.xml
- https://kennethwinner.com/posts/index.xml
- https://mdswanson.com/atom.xml
- https://oldchestnut.work/feed.xml
- https://roadfiresoftware.com/feed/
- https://t27duck.com/posts.xml
- https://trycatch.dev/rss.xml
- https://www.macksmind.io/feed.xml
title: IndyHackers Planet
about: Aggregating the IndyHackers Community
root_url: http://indyhackers-planet.herokuapp.com/
