name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "3 3 1 * *"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: ruby feed_healthcheck.rb
